/*
 * This file is generated by jOOQ.
 */
package DB.Tables.tables;


import DB.Tables.FootballsystemDb;
import DB.Tables.Keys;
import DB.Tables.tables.records.LeaguesRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row1;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Leagues extends TableImpl<LeaguesRecord> {

    private static final long serialVersionUID = -1239908654;

    /**
     * The reference instance of <code>footballsystem_db.leagues</code>
     */
    public static final Leagues LEAGUES = new Leagues();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<LeaguesRecord> getRecordType() {
        return LeaguesRecord.class;
    }

    /**
     * The column <code>footballsystem_db.leagues.name</code>.
     */
    public final TableField<LeaguesRecord, String> NAME = createField(DSL.name("name"), org.jooq.impl.SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * Create a <code>footballsystem_db.leagues</code> table reference
     */
    public Leagues() {
        this(DSL.name("leagues"), null);
    }

    /**
     * Create an aliased <code>footballsystem_db.leagues</code> table reference
     */
    public Leagues(String alias) {
        this(DSL.name(alias), LEAGUES);
    }

    /**
     * Create an aliased <code>footballsystem_db.leagues</code> table reference
     */
    public Leagues(Name alias) {
        this(alias, LEAGUES);
    }

    private Leagues(Name alias, Table<LeaguesRecord> aliased) {
        this(alias, aliased, null);
    }

    private Leagues(Name alias, Table<LeaguesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> Leagues(Table<O> child, ForeignKey<O, LeaguesRecord> key) {
        super(child, key, LEAGUES);
    }

    @Override
    public Schema getSchema() {
        return FootballsystemDb.FOOTBALLSYSTEM_DB;
    }

    @Override
    public UniqueKey<LeaguesRecord> getPrimaryKey() {
        return Keys.KEY_LEAGUES_PRIMARY;
    }

    @Override
    public List<UniqueKey<LeaguesRecord>> getKeys() {
        return Arrays.<UniqueKey<LeaguesRecord>>asList(Keys.KEY_LEAGUES_PRIMARY);
    }

    @Override
    public Leagues as(String alias) {
        return new Leagues(DSL.name(alias), this);
    }

    @Override
    public Leagues as(Name alias) {
        return new Leagues(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Leagues rename(String name) {
        return new Leagues(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Leagues rename(Name name) {
        return new Leagues(name, null);
    }

    // -------------------------------------------------------------------------
    // Row1 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row1<String> fieldsRow() {
        return (Row1) super.fieldsRow();
    }
}
