/*
 * This file is generated by jOOQ.
 */
package DB.Tables.tables;


import DB.Tables.FootballsystemDb;
import DB.Tables.Keys;
import DB.Tables.tables.records.TeamOwnerTeamsRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TeamOwnerTeams extends TableImpl<TeamOwnerTeamsRecord> {

    private static final long serialVersionUID = -903576033;

    /**
     * The reference instance of <code>footballsystem_db.team_owner_teams</code>
     */
    public static final TeamOwnerTeams TEAM_OWNER_TEAMS = new TeamOwnerTeams();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TeamOwnerTeamsRecord> getRecordType() {
        return TeamOwnerTeamsRecord.class;
    }

    /**
     * The column <code>footballsystem_db.team_owner_teams.team_owner</code>.
     */
    public final TableField<TeamOwnerTeamsRecord, String> TEAM_OWNER = createField(DSL.name("team_owner"), org.jooq.impl.SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>footballsystem_db.team_owner_teams.team_name</code>.
     */
    public final TableField<TeamOwnerTeamsRecord, String> TEAM_NAME = createField(DSL.name("team_name"), org.jooq.impl.SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * Create a <code>footballsystem_db.team_owner_teams</code> table reference
     */
    public TeamOwnerTeams() {
        this(DSL.name("team_owner_teams"), null);
    }

    /**
     * Create an aliased <code>footballsystem_db.team_owner_teams</code> table reference
     */
    public TeamOwnerTeams(String alias) {
        this(DSL.name(alias), TEAM_OWNER_TEAMS);
    }

    /**
     * Create an aliased <code>footballsystem_db.team_owner_teams</code> table reference
     */
    public TeamOwnerTeams(Name alias) {
        this(alias, TEAM_OWNER_TEAMS);
    }

    private TeamOwnerTeams(Name alias, Table<TeamOwnerTeamsRecord> aliased) {
        this(alias, aliased, null);
    }

    private TeamOwnerTeams(Name alias, Table<TeamOwnerTeamsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> TeamOwnerTeams(Table<O> child, ForeignKey<O, TeamOwnerTeamsRecord> key) {
        super(child, key, TEAM_OWNER_TEAMS);
    }

    @Override
    public Schema getSchema() {
        return FootballsystemDb.FOOTBALLSYSTEM_DB;
    }

    @Override
    public UniqueKey<TeamOwnerTeamsRecord> getPrimaryKey() {
        return Keys.KEY_TEAM_OWNER_TEAMS_PRIMARY;
    }

    @Override
    public List<UniqueKey<TeamOwnerTeamsRecord>> getKeys() {
        return Arrays.<UniqueKey<TeamOwnerTeamsRecord>>asList(Keys.KEY_TEAM_OWNER_TEAMS_PRIMARY);
    }

    @Override
    public List<ForeignKey<TeamOwnerTeamsRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<TeamOwnerTeamsRecord, ?>>asList(Keys.FK_TEAM_OWNER_TEAMS_FANS, Keys.FK_TEAM_OWNER_TEAMS_TEAMS);
    }

    public Fans fans() {
        return new Fans(this, Keys.FK_TEAM_OWNER_TEAMS_FANS);
    }

    public Teams teams() {
        return new Teams(this, Keys.FK_TEAM_OWNER_TEAMS_TEAMS);
    }

    @Override
    public TeamOwnerTeams as(String alias) {
        return new TeamOwnerTeams(DSL.name(alias), this);
    }

    @Override
    public TeamOwnerTeams as(Name alias) {
        return new TeamOwnerTeams(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TeamOwnerTeams rename(String name) {
        return new TeamOwnerTeams(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TeamOwnerTeams rename(Name name) {
        return new TeamOwnerTeams(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
