/*
 * This file is generated by jOOQ.
 */
package DB.Tables;


import DB.Tables.tables.Calculationpolicys;
import DB.Tables.tables.Coachs;
import DB.Tables.tables.Events;
import DB.Tables.tables.EventsOnePlayer;
import DB.Tables.tables.EventsTime;
import DB.Tables.tables.EventsTwoPlayers;
import DB.Tables.tables.FanMatchesFollow;
import DB.Tables.tables.FanNotification;
import DB.Tables.tables.Fans;
import DB.Tables.tables.FieldsInSystem;
import DB.Tables.tables.Leagues;
import DB.Tables.tables.Matches;
import DB.Tables.tables.Players;
import DB.Tables.tables.RefereeNotification;
import DB.Tables.tables.RefereeSeasonLeague;
import DB.Tables.tables.Referees;
import DB.Tables.tables.RefereesMatches;
import DB.Tables.tables.Rfas;
import DB.Tables.tables.Schedulingpolicys;
import DB.Tables.tables.SeasonLeagueTeam;
import DB.Tables.tables.Seasons;
import DB.Tables.tables.TeamOwnerApprovedTeams;
import DB.Tables.tables.TeamOwnerRequests;
import DB.Tables.tables.TeamOwnerTeams;
import DB.Tables.tables.Teamroles;
import DB.Tables.tables.Teams;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FootballsystemDb extends SchemaImpl {

    private static final long serialVersionUID = 1474863320;

    /**
     * The reference instance of <code>footballsystem_db</code>
     */
    public static final FootballsystemDb FOOTBALLSYSTEM_DB = new FootballsystemDb();

    /**
     * The table <code>footballsystem_db.calculationpolicys</code>.
     */
    public final Calculationpolicys CALCULATIONPOLICYS = Calculationpolicys.CALCULATIONPOLICYS;

    /**
     * The table <code>footballsystem_db.coachs</code>.
     */
    public final Coachs COACHS = Coachs.COACHS;

    /**
     * The table <code>footballsystem_db.events</code>.
     */
    public final Events EVENTS = Events.EVENTS;

    /**
     * The table <code>footballsystem_db.events_one_player</code>.
     */
    public final EventsOnePlayer EVENTS_ONE_PLAYER = EventsOnePlayer.EVENTS_ONE_PLAYER;

    /**
     * The table <code>footballsystem_db.events_time</code>.
     */
    public final EventsTime EVENTS_TIME = EventsTime.EVENTS_TIME;

    /**
     * The table <code>footballsystem_db.events_two_players</code>.
     */
    public final EventsTwoPlayers EVENTS_TWO_PLAYERS = EventsTwoPlayers.EVENTS_TWO_PLAYERS;

    /**
     * The table <code>footballsystem_db.fan_matches_follow</code>.
     */
    public final FanMatchesFollow FAN_MATCHES_FOLLOW = FanMatchesFollow.FAN_MATCHES_FOLLOW;

    /**
     * The table <code>footballsystem_db.fan_notification</code>.
     */
    public final FanNotification FAN_NOTIFICATION = FanNotification.FAN_NOTIFICATION;

    /**
     * The table <code>footballsystem_db.fans</code>.
     */
    public final Fans FANS = Fans.FANS;

    /**
     * The table <code>footballsystem_db.fields_in_system</code>.
     */
    public final FieldsInSystem FIELDS_IN_SYSTEM = FieldsInSystem.FIELDS_IN_SYSTEM;

    /**
     * The table <code>footballsystem_db.leagues</code>.
     */
    public final Leagues LEAGUES = Leagues.LEAGUES;

    /**
     * The table <code>footballsystem_db.matches</code>.
     */
    public final Matches MATCHES = Matches.MATCHES;

    /**
     * The table <code>footballsystem_db.players</code>.
     */
    public final Players PLAYERS = Players.PLAYERS;

    /**
     * The table <code>footballsystem_db.referee_notification</code>.
     */
    public final RefereeNotification REFEREE_NOTIFICATION = RefereeNotification.REFEREE_NOTIFICATION;

    /**
     * The table <code>footballsystem_db.referee_season_league</code>.
     */
    public final RefereeSeasonLeague REFEREE_SEASON_LEAGUE = RefereeSeasonLeague.REFEREE_SEASON_LEAGUE;

    /**
     * The table <code>footballsystem_db.referees</code>.
     */
    public final Referees REFEREES = Referees.REFEREES;

    /**
     * The table <code>footballsystem_db.referees_matches</code>.
     */
    public final RefereesMatches REFEREES_MATCHES = RefereesMatches.REFEREES_MATCHES;

    /**
     * The table <code>footballsystem_db.rfas</code>.
     */
    public final Rfas RFAS = Rfas.RFAS;

    /**
     * The table <code>footballsystem_db.schedulingpolicys</code>.
     */
    public final Schedulingpolicys SCHEDULINGPOLICYS = Schedulingpolicys.SCHEDULINGPOLICYS;

    /**
     * The table <code>footballsystem_db.season_league_team</code>.
     */
    public final SeasonLeagueTeam SEASON_LEAGUE_TEAM = SeasonLeagueTeam.SEASON_LEAGUE_TEAM;

    /**
     * The table <code>footballsystem_db.seasons</code>.
     */
    public final Seasons SEASONS = Seasons.SEASONS;

    /**
     * The table <code>footballsystem_db.team_owner_approved_teams</code>.
     */
    public final TeamOwnerApprovedTeams TEAM_OWNER_APPROVED_TEAMS = TeamOwnerApprovedTeams.TEAM_OWNER_APPROVED_TEAMS;

    /**
     * The table <code>footballsystem_db.team_owner_requests</code>.
     */
    public final TeamOwnerRequests TEAM_OWNER_REQUESTS = TeamOwnerRequests.TEAM_OWNER_REQUESTS;

    /**
     * The table <code>footballsystem_db.team_owner_teams</code>.
     */
    public final TeamOwnerTeams TEAM_OWNER_TEAMS = TeamOwnerTeams.TEAM_OWNER_TEAMS;

    /**
     * The table <code>footballsystem_db.teamroles</code>.
     */
    public final Teamroles TEAMROLES = Teamroles.TEAMROLES;

    /**
     * The table <code>footballsystem_db.teams</code>.
     */
    public final Teams TEAMS = Teams.TEAMS;

    /**
     * No further instances allowed
     */
    private FootballsystemDb() {
        super("footballsystem_db", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            Calculationpolicys.CALCULATIONPOLICYS,
            Coachs.COACHS,
            Events.EVENTS,
            EventsOnePlayer.EVENTS_ONE_PLAYER,
            EventsTime.EVENTS_TIME,
            EventsTwoPlayers.EVENTS_TWO_PLAYERS,
            FanMatchesFollow.FAN_MATCHES_FOLLOW,
            FanNotification.FAN_NOTIFICATION,
            Fans.FANS,
            FieldsInSystem.FIELDS_IN_SYSTEM,
            Leagues.LEAGUES,
            Matches.MATCHES,
            Players.PLAYERS,
            RefereeNotification.REFEREE_NOTIFICATION,
            RefereeSeasonLeague.REFEREE_SEASON_LEAGUE,
            Referees.REFEREES,
            RefereesMatches.REFEREES_MATCHES,
            Rfas.RFAS,
            Schedulingpolicys.SCHEDULINGPOLICYS,
            SeasonLeagueTeam.SEASON_LEAGUE_TEAM,
            Seasons.SEASONS,
            TeamOwnerApprovedTeams.TEAM_OWNER_APPROVED_TEAMS,
            TeamOwnerRequests.TEAM_OWNER_REQUESTS,
            TeamOwnerTeams.TEAM_OWNER_TEAMS,
            Teamroles.TEAMROLES,
            Teams.TEAMS);
    }
}
