/*
 * This file is generated by jOOQ.
 */
package DB.Tables;


import DB.Tables.tables.Fans;
import DB.Tables.tables.Matches;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FootballsystemDb extends SchemaImpl {

    private static final long serialVersionUID = 1247458720;

    /**
     * The reference instance of <code>footballsystem_db</code>
     */
    public static final FootballsystemDb FOOTBALLSYSTEM_DB = new FootballsystemDb();

    /**
     * The table <code>footballsystem_db.fans</code>.
     */
    public final Fans FANS = Fans.FANS;

    /**
     * The table <code>footballsystem_db.matches</code>.
     */
    public final Matches MATCHES = Matches.MATCHES;

    /**
     * No further instances allowed
     */
    private FootballsystemDb() {
        super("footballsystem_db", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            Fans.FANS,
            Matches.MATCHES);
    }
}
