/*
 * This file is generated by jOOQ.
 */
package DB.Tables;


import DB.Tables.tables.Matches;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>footballsystem_db</code> 
 * schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index MATCHES_HOME_TEAM = Indexes0.MATCHES_HOME_TEAM;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index MATCHES_HOME_TEAM = Internal.createIndex("home_team", Matches.MATCHES, new OrderField[] { Matches.MATCHES.HOME_TEAM }, false);
    }
}
