/*
 * This file is generated by jOOQ.
 */
package DB.Tables;


import DB.Tables.tables.Fans;
import DB.Tables.tables.records.FansRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>footballsystem_db</code> schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<FansRecord> KEY_FANS_PRIMARY = UniqueKeys0.KEY_FANS_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 {
        public static final UniqueKey<FansRecord> KEY_FANS_PRIMARY = Internal.createUniqueKey(Fans.FANS, "KEY_fans_PRIMARY", new TableField[] { Fans.FANS.USERNAME }, true);
    }
}
