/*
 * This file is generated by jOOQ.
 */
package DB.Tables;


import DB.Tables.tables.Calculationpolicys;
import DB.Tables.tables.Coachs;
import DB.Tables.tables.Events;
import DB.Tables.tables.EventsOnePlayer;
import DB.Tables.tables.EventsTime;
import DB.Tables.tables.EventsTwoPlayers;
import DB.Tables.tables.FanMatchesFollow;
import DB.Tables.tables.FanNotification;
import DB.Tables.tables.Fans;
import DB.Tables.tables.FieldsInSystem;
import DB.Tables.tables.Leagues;
import DB.Tables.tables.Matches;
import DB.Tables.tables.Players;
import DB.Tables.tables.RefereeNotification;
import DB.Tables.tables.RefereeSeasonLeague;
import DB.Tables.tables.Referees;
import DB.Tables.tables.RefereesMatches;
import DB.Tables.tables.Rfas;
import DB.Tables.tables.Schedulingpolicys;
import DB.Tables.tables.SeasonLeagueTeam;
import DB.Tables.tables.Seasons;
import DB.Tables.tables.TeamOwnerApprovedTeams;
import DB.Tables.tables.TeamOwnerRequests;
import DB.Tables.tables.TeamOwnerTeams;
import DB.Tables.tables.Teamroles;
import DB.Tables.tables.Teams;


/**
 * Convenience access to all tables in footballsystem_db
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>footballsystem_db.calculationpolicys</code>.
     */
    public static final Calculationpolicys CALCULATIONPOLICYS = Calculationpolicys.CALCULATIONPOLICYS;

    /**
     * The table <code>footballsystem_db.coachs</code>.
     */
    public static final Coachs COACHS = Coachs.COACHS;

    /**
     * The table <code>footballsystem_db.events</code>.
     */
    public static final Events EVENTS = Events.EVENTS;

    /**
     * The table <code>footballsystem_db.events_one_player</code>.
     */
    public static final EventsOnePlayer EVENTS_ONE_PLAYER = EventsOnePlayer.EVENTS_ONE_PLAYER;

    /**
     * The table <code>footballsystem_db.events_time</code>.
     */
    public static final EventsTime EVENTS_TIME = EventsTime.EVENTS_TIME;

    /**
     * The table <code>footballsystem_db.events_two_players</code>.
     */
    public static final EventsTwoPlayers EVENTS_TWO_PLAYERS = EventsTwoPlayers.EVENTS_TWO_PLAYERS;

    /**
     * The table <code>footballsystem_db.fan_matches_follow</code>.
     */
    public static final FanMatchesFollow FAN_MATCHES_FOLLOW = FanMatchesFollow.FAN_MATCHES_FOLLOW;

    /**
     * The table <code>footballsystem_db.fan_notification</code>.
     */
    public static final FanNotification FAN_NOTIFICATION = FanNotification.FAN_NOTIFICATION;

    /**
     * The table <code>footballsystem_db.fans</code>.
     */
    public static final Fans FANS = Fans.FANS;

    /**
     * The table <code>footballsystem_db.fields_in_system</code>.
     */
    public static final FieldsInSystem FIELDS_IN_SYSTEM = FieldsInSystem.FIELDS_IN_SYSTEM;

    /**
     * The table <code>footballsystem_db.leagues</code>.
     */
    public static final Leagues LEAGUES = Leagues.LEAGUES;

    /**
     * The table <code>footballsystem_db.matches</code>.
     */
    public static final Matches MATCHES = Matches.MATCHES;

    /**
     * The table <code>footballsystem_db.players</code>.
     */
    public static final Players PLAYERS = Players.PLAYERS;

    /**
     * The table <code>footballsystem_db.referee_notification</code>.
     */
    public static final RefereeNotification REFEREE_NOTIFICATION = RefereeNotification.REFEREE_NOTIFICATION;

    /**
     * The table <code>footballsystem_db.referee_season_league</code>.
     */
    public static final RefereeSeasonLeague REFEREE_SEASON_LEAGUE = RefereeSeasonLeague.REFEREE_SEASON_LEAGUE;

    /**
     * The table <code>footballsystem_db.referees</code>.
     */
    public static final Referees REFEREES = Referees.REFEREES;

    /**
     * The table <code>footballsystem_db.referees_matches</code>.
     */
    public static final RefereesMatches REFEREES_MATCHES = RefereesMatches.REFEREES_MATCHES;

    /**
     * The table <code>footballsystem_db.rfas</code>.
     */
    public static final Rfas RFAS = Rfas.RFAS;

    /**
     * The table <code>footballsystem_db.schedulingpolicys</code>.
     */
    public static final Schedulingpolicys SCHEDULINGPOLICYS = Schedulingpolicys.SCHEDULINGPOLICYS;

    /**
     * The table <code>footballsystem_db.season_league_team</code>.
     */
    public static final SeasonLeagueTeam SEASON_LEAGUE_TEAM = SeasonLeagueTeam.SEASON_LEAGUE_TEAM;

    /**
     * The table <code>footballsystem_db.seasons</code>.
     */
    public static final Seasons SEASONS = Seasons.SEASONS;

    /**
     * The table <code>footballsystem_db.team_owner_approved_teams</code>.
     */
    public static final TeamOwnerApprovedTeams TEAM_OWNER_APPROVED_TEAMS = TeamOwnerApprovedTeams.TEAM_OWNER_APPROVED_TEAMS;

    /**
     * The table <code>footballsystem_db.team_owner_requests</code>.
     */
    public static final TeamOwnerRequests TEAM_OWNER_REQUESTS = TeamOwnerRequests.TEAM_OWNER_REQUESTS;

    /**
     * The table <code>footballsystem_db.team_owner_teams</code>.
     */
    public static final TeamOwnerTeams TEAM_OWNER_TEAMS = TeamOwnerTeams.TEAM_OWNER_TEAMS;

    /**
     * The table <code>footballsystem_db.teamroles</code>.
     */
    public static final Teamroles TEAMROLES = Teamroles.TEAMROLES;

    /**
     * The table <code>footballsystem_db.teams</code>.
     */
    public static final Teams TEAMS = Teams.TEAMS;
}
