/*
 * This file is generated by jOOQ.
 */
package DB.Tables;


import DB.Tables.tables.Fans;
import DB.Tables.tables.Matches;


/**
 * Convenience access to all tables in footballsystem_db
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>footballsystem_db.fans</code>.
     */
    public static final Fans FANS = Fans.FANS;

    /**
     * The table <code>footballsystem_db.matches</code>.
     */
    public static final Matches MATCHES = Matches.MATCHES;
}
