/*
 * This file is generated by jOOQ.
 */
package DB.Tables.tables.records;


import DB.Tables.tables.Calculationpolicys;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Row1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CalculationpolicysRecord extends UpdatableRecordImpl<CalculationpolicysRecord> implements Record1<String> {

    private static final long serialVersionUID = -371611699;

    /**
     * Setter for <code>footballsystem_db.calculationpolicys.name</code>.
     */
    public void setName(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>footballsystem_db.calculationpolicys.name</code>.
     */
    public String getName() {
        return (String) get(0);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record1 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row1<String> fieldsRow() {
        return (Row1) super.fieldsRow();
    }

    @Override
    public Row1<String> valuesRow() {
        return (Row1) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return Calculationpolicys.CALCULATIONPOLICYS.NAME;
    }

    @Override
    public String component1() {
        return getName();
    }

    @Override
    public String value1() {
        return getName();
    }

    @Override
    public CalculationpolicysRecord value1(String value) {
        setName(value);
        return this;
    }

    @Override
    public CalculationpolicysRecord values(String value1) {
        value1(value1);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CalculationpolicysRecord
     */
    public CalculationpolicysRecord() {
        super(Calculationpolicys.CALCULATIONPOLICYS);
    }

    /**
     * Create a detached, initialised CalculationpolicysRecord
     */
    public CalculationpolicysRecord(String name) {
        super(Calculationpolicys.CALCULATIONPOLICYS);

        set(0, name);
    }
}
