/*
 * This file is generated by jOOQ.
 */
package DB.Tables.tables.records;


import DB.Tables.tables.EventsOnePlayer;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EventsOnePlayerRecord extends UpdatableRecordImpl<EventsOnePlayerRecord> implements Record2<Integer, String> {

    private static final long serialVersionUID = 1905713063;

    /**
     * Setter for <code>footballsystem_db.events_one_player.event_id</code>.
     */
    public void setEventId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>footballsystem_db.events_one_player.event_id</code>.
     */
    public Integer getEventId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>footballsystem_db.events_one_player.player1</code>.
     */
    public void setPlayer1(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>footballsystem_db.events_one_player.player1</code>.
     */
    public String getPlayer1() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return EventsOnePlayer.EVENTS_ONE_PLAYER.EVENT_ID;
    }

    @Override
    public Field<String> field2() {
        return EventsOnePlayer.EVENTS_ONE_PLAYER.PLAYER1;
    }

    @Override
    public Integer component1() {
        return getEventId();
    }

    @Override
    public String component2() {
        return getPlayer1();
    }

    @Override
    public Integer value1() {
        return getEventId();
    }

    @Override
    public String value2() {
        return getPlayer1();
    }

    @Override
    public EventsOnePlayerRecord value1(Integer value) {
        setEventId(value);
        return this;
    }

    @Override
    public EventsOnePlayerRecord value2(String value) {
        setPlayer1(value);
        return this;
    }

    @Override
    public EventsOnePlayerRecord values(Integer value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EventsOnePlayerRecord
     */
    public EventsOnePlayerRecord() {
        super(EventsOnePlayer.EVENTS_ONE_PLAYER);
    }

    /**
     * Create a detached, initialised EventsOnePlayerRecord
     */
    public EventsOnePlayerRecord(Integer eventId, String player1) {
        super(EventsOnePlayer.EVENTS_ONE_PLAYER);

        set(0, eventId);
        set(1, player1);
    }
}
