/*
 * This file is generated by jOOQ.
 */
package DB.Tables.tables.records;


import DB.Tables.tables.FanNotification;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FanNotificationRecord extends TableRecordImpl<FanNotificationRecord> {

    private static final long serialVersionUID = -1600492006;

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FanNotificationRecord
     */
    public FanNotificationRecord() {
        super(FanNotification.FAN_NOTIFICATION);
    }
}
