/*
 * This file is generated by jOOQ.
 */
package DB.Tables.tables.records;


import DB.Tables.tables.Leagues;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Row1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LeaguesRecord extends UpdatableRecordImpl<LeaguesRecord> implements Record1<String> {

    private static final long serialVersionUID = -910273873;

    /**
     * Setter for <code>footballsystem_db.leagues.name</code>.
     */
    public void setName(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>footballsystem_db.leagues.name</code>.
     */
    public String getName() {
        return (String) get(0);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record1 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row1<String> fieldsRow() {
        return (Row1) super.fieldsRow();
    }

    @Override
    public Row1<String> valuesRow() {
        return (Row1) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return Leagues.LEAGUES.NAME;
    }

    @Override
    public String component1() {
        return getName();
    }

    @Override
    public String value1() {
        return getName();
    }

    @Override
    public LeaguesRecord value1(String value) {
        setName(value);
        return this;
    }

    @Override
    public LeaguesRecord values(String value1) {
        value1(value1);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LeaguesRecord
     */
    public LeaguesRecord() {
        super(Leagues.LEAGUES);
    }

    /**
     * Create a detached, initialised LeaguesRecord
     */
    public LeaguesRecord(String name) {
        super(Leagues.LEAGUES);

        set(0, name);
    }
}
