/*
 * This file is generated by jOOQ.
 */
package DB.Tables.tables.records;


import DB.Tables.tables.Players;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PlayersRecord extends UpdatableRecordImpl<PlayersRecord> implements Record3<String, String, String> {

    private static final long serialVersionUID = -944761874;

    /**
     * Setter for <code>footballsystem_db.players.userName</code>.
     */
    public void setUsername(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>footballsystem_db.players.userName</code>.
     */
    public String getUsername() {
        return (String) get(0);
    }

    /**
     * Setter for <code>footballsystem_db.players.playerTeamName</code>.
     */
    public void setPlayerteamname(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>footballsystem_db.players.playerTeamName</code>.
     */
    public String getPlayerteamname() {
        return (String) get(1);
    }

    /**
     * Setter for <code>footballsystem_db.players.roleAtField</code>.
     */
    public void setRoleatfield(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>footballsystem_db.players.roleAtField</code>.
     */
    public String getRoleatfield() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<String, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<String, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return Players.PLAYERS.USERNAME;
    }

    @Override
    public Field<String> field2() {
        return Players.PLAYERS.PLAYERTEAMNAME;
    }

    @Override
    public Field<String> field3() {
        return Players.PLAYERS.ROLEATFIELD;
    }

    @Override
    public String component1() {
        return getUsername();
    }

    @Override
    public String component2() {
        return getPlayerteamname();
    }

    @Override
    public String component3() {
        return getRoleatfield();
    }

    @Override
    public String value1() {
        return getUsername();
    }

    @Override
    public String value2() {
        return getPlayerteamname();
    }

    @Override
    public String value3() {
        return getRoleatfield();
    }

    @Override
    public PlayersRecord value1(String value) {
        setUsername(value);
        return this;
    }

    @Override
    public PlayersRecord value2(String value) {
        setPlayerteamname(value);
        return this;
    }

    @Override
    public PlayersRecord value3(String value) {
        setRoleatfield(value);
        return this;
    }

    @Override
    public PlayersRecord values(String value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PlayersRecord
     */
    public PlayersRecord() {
        super(Players.PLAYERS);
    }

    /**
     * Create a detached, initialised PlayersRecord
     */
    public PlayersRecord(String username, String playerteamname, String roleatfield) {
        super(Players.PLAYERS);

        set(0, username);
        set(1, playerteamname);
        set(2, roleatfield);
    }
}
