/*
 * This file is generated by jOOQ.
 */
package DB.Tables.tables.records;


import DB.Tables.tables.RefereeSeasonLeague;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RefereeSeasonLeagueRecord extends UpdatableRecordImpl<RefereeSeasonLeagueRecord> implements Record3<String, String, String> {

    private static final long serialVersionUID = -24450253;

    /**
     * Setter for <code>footballsystem_db.referee_season_league.referee</code>.
     */
    public void setReferee(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>footballsystem_db.referee_season_league.referee</code>.
     */
    public String getReferee() {
        return (String) get(0);
    }

    /**
     * Setter for <code>footballsystem_db.referee_season_league.season_year</code>.
     */
    public void setSeasonYear(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>footballsystem_db.referee_season_league.season_year</code>.
     */
    public String getSeasonYear() {
        return (String) get(1);
    }

    /**
     * Setter for <code>footballsystem_db.referee_season_league.league_name</code>.
     */
    public void setLeagueName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>footballsystem_db.referee_season_league.league_name</code>.
     */
    public String getLeagueName() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record3<String, String, String> key() {
        return (Record3) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<String, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<String, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return RefereeSeasonLeague.REFEREE_SEASON_LEAGUE.REFEREE;
    }

    @Override
    public Field<String> field2() {
        return RefereeSeasonLeague.REFEREE_SEASON_LEAGUE.SEASON_YEAR;
    }

    @Override
    public Field<String> field3() {
        return RefereeSeasonLeague.REFEREE_SEASON_LEAGUE.LEAGUE_NAME;
    }

    @Override
    public String component1() {
        return getReferee();
    }

    @Override
    public String component2() {
        return getSeasonYear();
    }

    @Override
    public String component3() {
        return getLeagueName();
    }

    @Override
    public String value1() {
        return getReferee();
    }

    @Override
    public String value2() {
        return getSeasonYear();
    }

    @Override
    public String value3() {
        return getLeagueName();
    }

    @Override
    public RefereeSeasonLeagueRecord value1(String value) {
        setReferee(value);
        return this;
    }

    @Override
    public RefereeSeasonLeagueRecord value2(String value) {
        setSeasonYear(value);
        return this;
    }

    @Override
    public RefereeSeasonLeagueRecord value3(String value) {
        setLeagueName(value);
        return this;
    }

    @Override
    public RefereeSeasonLeagueRecord values(String value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RefereeSeasonLeagueRecord
     */
    public RefereeSeasonLeagueRecord() {
        super(RefereeSeasonLeague.REFEREE_SEASON_LEAGUE);
    }

    /**
     * Create a detached, initialised RefereeSeasonLeagueRecord
     */
    public RefereeSeasonLeagueRecord(String referee, String seasonYear, String leagueName) {
        super(RefereeSeasonLeague.REFEREE_SEASON_LEAGUE);

        set(0, referee);
        set(1, seasonYear);
        set(2, leagueName);
    }
}
