/*
 * This file is generated by jOOQ.
 */
package DB.Tables.tables.records;


import DB.Tables.tables.RefereeNotification;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RefereeNotificationRecord extends TableRecordImpl<RefereeNotificationRecord> {

    private static final long serialVersionUID = 729293063;

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RefereeNotificationRecord
     */
    public RefereeNotificationRecord() {
        super(RefereeNotification.REFEREE_NOTIFICATION);
    }
}
