/*
 * This file is generated by jOOQ.
 */
package DB.Tables.tables.records;


import DB.Tables.tables.Referees;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RefereesRecord extends UpdatableRecordImpl<RefereesRecord> implements Record2<String, String> {

    private static final long serialVersionUID = 229145487;

    /**
     * Setter for <code>footballsystem_db.referees.userName</code>.
     */
    public void setUsername(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>footballsystem_db.referees.userName</code>.
     */
    public String getUsername() {
        return (String) get(0);
    }

    /**
     * Setter for <code>footballsystem_db.referees.qualification</code>.
     */
    public void setQualification(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>footballsystem_db.referees.qualification</code>.
     */
    public String getQualification() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<String, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return Referees.REFEREES.USERNAME;
    }

    @Override
    public Field<String> field2() {
        return Referees.REFEREES.QUALIFICATION;
    }

    @Override
    public String component1() {
        return getUsername();
    }

    @Override
    public String component2() {
        return getQualification();
    }

    @Override
    public String value1() {
        return getUsername();
    }

    @Override
    public String value2() {
        return getQualification();
    }

    @Override
    public RefereesRecord value1(String value) {
        setUsername(value);
        return this;
    }

    @Override
    public RefereesRecord value2(String value) {
        setQualification(value);
        return this;
    }

    @Override
    public RefereesRecord values(String value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RefereesRecord
     */
    public RefereesRecord() {
        super(Referees.REFEREES);
    }

    /**
     * Create a detached, initialised RefereesRecord
     */
    public RefereesRecord(String username, String qualification) {
        super(Referees.REFEREES);

        set(0, username);
        set(1, qualification);
    }
}
