/*
 * This file is generated by jOOQ.
 */
package DB.Tables.tables.records;


import DB.Tables.tables.Rfas;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Row1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RfasRecord extends UpdatableRecordImpl<RfasRecord> implements Record1<String> {

    private static final long serialVersionUID = 229176103;

    /**
     * Setter for <code>footballsystem_db.rfas.userName</code>.
     */
    public void setUsername(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>footballsystem_db.rfas.userName</code>.
     */
    public String getUsername() {
        return (String) get(0);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record1 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row1<String> fieldsRow() {
        return (Row1) super.fieldsRow();
    }

    @Override
    public Row1<String> valuesRow() {
        return (Row1) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return Rfas.RFAS.USERNAME;
    }

    @Override
    public String component1() {
        return getUsername();
    }

    @Override
    public String value1() {
        return getUsername();
    }

    @Override
    public RfasRecord value1(String value) {
        setUsername(value);
        return this;
    }

    @Override
    public RfasRecord values(String value1) {
        value1(value1);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RfasRecord
     */
    public RfasRecord() {
        super(Rfas.RFAS);
    }

    /**
     * Create a detached, initialised RfasRecord
     */
    public RfasRecord(String username) {
        super(Rfas.RFAS);

        set(0, username);
    }
}
