/*
 * This file is generated by jOOQ.
 */
package DB.Tables.tables.records;


import DB.Tables.tables.Schedulingpolicys;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Row1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SchedulingpolicysRecord extends UpdatableRecordImpl<SchedulingpolicysRecord> implements Record1<String> {

    private static final long serialVersionUID = -1076839126;

    /**
     * Setter for <code>footballsystem_db.schedulingpolicys.name</code>.
     */
    public void setName(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>footballsystem_db.schedulingpolicys.name</code>.
     */
    public String getName() {
        return (String) get(0);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record1 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row1<String> fieldsRow() {
        return (Row1) super.fieldsRow();
    }

    @Override
    public Row1<String> valuesRow() {
        return (Row1) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return Schedulingpolicys.SCHEDULINGPOLICYS.NAME;
    }

    @Override
    public String component1() {
        return getName();
    }

    @Override
    public String value1() {
        return getName();
    }

    @Override
    public SchedulingpolicysRecord value1(String value) {
        setName(value);
        return this;
    }

    @Override
    public SchedulingpolicysRecord values(String value1) {
        value1(value1);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SchedulingpolicysRecord
     */
    public SchedulingpolicysRecord() {
        super(Schedulingpolicys.SCHEDULINGPOLICYS);
    }

    /**
     * Create a detached, initialised SchedulingpolicysRecord
     */
    public SchedulingpolicysRecord(String name) {
        super(Schedulingpolicys.SCHEDULINGPOLICYS);

        set(0, name);
    }
}
