/*
 * This file is generated by jOOQ.
 */
package DB.Tables.tables.records;


import DB.Tables.tables.SeasonLeagueTeam;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SeasonLeagueTeamRecord extends UpdatableRecordImpl<SeasonLeagueTeamRecord> implements Record3<String, String, String> {

    private static final long serialVersionUID = 265747767;

    /**
     * Setter for <code>footballsystem_db.season_league_team.season_year</code>.
     */
    public void setSeasonYear(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>footballsystem_db.season_league_team.season_year</code>.
     */
    public String getSeasonYear() {
        return (String) get(0);
    }

    /**
     * Setter for <code>footballsystem_db.season_league_team.league_name</code>.
     */
    public void setLeagueName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>footballsystem_db.season_league_team.league_name</code>.
     */
    public String getLeagueName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>footballsystem_db.season_league_team.team_name</code>.
     */
    public void setTeamName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>footballsystem_db.season_league_team.team_name</code>.
     */
    public String getTeamName() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record3<String, String, String> key() {
        return (Record3) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<String, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<String, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return SeasonLeagueTeam.SEASON_LEAGUE_TEAM.SEASON_YEAR;
    }

    @Override
    public Field<String> field2() {
        return SeasonLeagueTeam.SEASON_LEAGUE_TEAM.LEAGUE_NAME;
    }

    @Override
    public Field<String> field3() {
        return SeasonLeagueTeam.SEASON_LEAGUE_TEAM.TEAM_NAME;
    }

    @Override
    public String component1() {
        return getSeasonYear();
    }

    @Override
    public String component2() {
        return getLeagueName();
    }

    @Override
    public String component3() {
        return getTeamName();
    }

    @Override
    public String value1() {
        return getSeasonYear();
    }

    @Override
    public String value2() {
        return getLeagueName();
    }

    @Override
    public String value3() {
        return getTeamName();
    }

    @Override
    public SeasonLeagueTeamRecord value1(String value) {
        setSeasonYear(value);
        return this;
    }

    @Override
    public SeasonLeagueTeamRecord value2(String value) {
        setLeagueName(value);
        return this;
    }

    @Override
    public SeasonLeagueTeamRecord value3(String value) {
        setTeamName(value);
        return this;
    }

    @Override
    public SeasonLeagueTeamRecord values(String value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SeasonLeagueTeamRecord
     */
    public SeasonLeagueTeamRecord() {
        super(SeasonLeagueTeam.SEASON_LEAGUE_TEAM);
    }

    /**
     * Create a detached, initialised SeasonLeagueTeamRecord
     */
    public SeasonLeagueTeamRecord(String seasonYear, String leagueName, String teamName) {
        super(SeasonLeagueTeam.SEASON_LEAGUE_TEAM);

        set(0, seasonYear);
        set(1, leagueName);
        set(2, teamName);
    }
}
