/*
 * This file is generated by jOOQ.
 */
package DB.Tables.tables.records;


import DB.Tables.tables.Teams;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TeamsRecord extends UpdatableRecordImpl<TeamsRecord> implements Record6<String, String, String, String, String, Integer> {

    private static final long serialVersionUID = -1200283561;

    /**
     * Setter for <code>footballsystem_db.teams.teamName</code>.
     */
    public void setTeamname(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>footballsystem_db.teams.teamName</code>.
     */
    public String getTeamname() {
        return (String) get(0);
    }

    /**
     * Setter for <code>footballsystem_db.teams.teamManager</code>.
     */
    public void setTeammanager(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>footballsystem_db.teams.teamManager</code>.
     */
    public String getTeammanager() {
        return (String) get(1);
    }

    /**
     * Setter for <code>footballsystem_db.teams.founder</code>.
     */
    public void setFounder(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>footballsystem_db.teams.founder</code>.
     */
    public String getFounder() {
        return (String) get(2);
    }

    /**
     * Setter for <code>footballsystem_db.teams.coach</code>.
     */
    public void setCoach(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>footballsystem_db.teams.coach</code>.
     */
    public String getCoach() {
        return (String) get(3);
    }

    /**
     * Setter for <code>footballsystem_db.teams.field</code>.
     */
    public void setField(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>footballsystem_db.teams.field</code>.
     */
    public String getField() {
        return (String) get(4);
    }

    /**
     * Setter for <code>footballsystem_db.teams.score</code>.
     */
    public void setScore(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>footballsystem_db.teams.score</code>.
     */
    public Integer getScore() {
        return (Integer) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<String, String, String, String, String, Integer> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<String, String, String, String, String, Integer> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return Teams.TEAMS.TEAMNAME;
    }

    @Override
    public Field<String> field2() {
        return Teams.TEAMS.TEAMMANAGER;
    }

    @Override
    public Field<String> field3() {
        return Teams.TEAMS.FOUNDER;
    }

    @Override
    public Field<String> field4() {
        return Teams.TEAMS.COACH;
    }

    @Override
    public Field<String> field5() {
        return Teams.TEAMS.FIELD;
    }

    @Override
    public Field<Integer> field6() {
        return Teams.TEAMS.SCORE;
    }

    @Override
    public String component1() {
        return getTeamname();
    }

    @Override
    public String component2() {
        return getTeammanager();
    }

    @Override
    public String component3() {
        return getFounder();
    }

    @Override
    public String component4() {
        return getCoach();
    }

    @Override
    public String component5() {
        return getField();
    }

    @Override
    public Integer component6() {
        return getScore();
    }

    @Override
    public String value1() {
        return getTeamname();
    }

    @Override
    public String value2() {
        return getTeammanager();
    }

    @Override
    public String value3() {
        return getFounder();
    }

    @Override
    public String value4() {
        return getCoach();
    }

    @Override
    public String value5() {
        return getField();
    }

    @Override
    public Integer value6() {
        return getScore();
    }

    @Override
    public TeamsRecord value1(String value) {
        setTeamname(value);
        return this;
    }

    @Override
    public TeamsRecord value2(String value) {
        setTeammanager(value);
        return this;
    }

    @Override
    public TeamsRecord value3(String value) {
        setFounder(value);
        return this;
    }

    @Override
    public TeamsRecord value4(String value) {
        setCoach(value);
        return this;
    }

    @Override
    public TeamsRecord value5(String value) {
        setField(value);
        return this;
    }

    @Override
    public TeamsRecord value6(Integer value) {
        setScore(value);
        return this;
    }

    @Override
    public TeamsRecord values(String value1, String value2, String value3, String value4, String value5, Integer value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TeamsRecord
     */
    public TeamsRecord() {
        super(Teams.TEAMS);
    }

    /**
     * Create a detached, initialised TeamsRecord
     */
    public TeamsRecord(String teamname, String teammanager, String founder, String coach, String field, Integer score) {
        super(Teams.TEAMS);

        set(0, teamname);
        set(1, teammanager);
        set(2, founder);
        set(3, coach);
        set(4, field);
        set(5, score);
    }
}
